### ISSUE TITLE
Reg. Django Admin admin panel  

### ISSUE THREAD

**Issue by anush0247** [Miserlou/django-zappa#18]
when i tried to use django zappa for configure the django admin panel. session get logged out for every two subsequent clicks. I was unable to reach till adding a uses from django zappa based admin panel. I thought zappa cokkie getting expired.

**Comment by Miserlou** [comment]
Can you explain "adding a uses from django zappa based admin panel" a bit more? I don't understand.

**Comment by anush0247** [comment]
I can able to login to the django admin panel. Through admin panel, i tried access users list, add tried add new user. I got the user addition form. while submitting the form. users gets logged out. Browser redirected to login page. Process get repeated on every attempt

**Comment by bjinwright** [comment]
I can confirm this

**Comment by Miserlou** [comment]
I'm 90% sure I know what this (and it's fixed in core) - but just to help me diagnose/reproduce - is the user created upon form submission?

Also - are you using the application on a domain, or on the raw APIGW URL?

**Comment by bjinwright** [comment]
Are you sure it's not because the sessionid and csrftoken cookies aren't set.

**Comment by Miserlou** [comment]
That's my current diagnosis. This is fixed in the Zappa-core middleware, which D-Z is not using - yet! See https://github.com/Miserlou/django-zappa/issues/52

Again, I hope that this will be fixed be E.O.D. If not, it should be soon, this is the current Zappa priority. Thanks for your patience.

**Comment by Miserlou** [comment]
The other benefit of this is that it means that you won't have to add ZappaMiddleware to your Django config anymore.

**Comment by Miserlou** [comment]
Confirming this for myself.. {"message": "Could not parse request body into json: Unexpected character (\'-\' (code 45)) in numeric value: expected digit (0-9) to follow minus sign, for valid numeric value\n at [Source: [B@64744c6; line: 1, column: 3]"}

**Comment by Miserlou** [comment]
Weirdly enough, this may be because the django-admin defaults to "multipart/form-data".. investigating..

**Comment by bjinwright** [comment]
Here is a screenshot of what parsed and unparsed session cookies I'm seeing. https://s3.amazonaws.com/ipoots-zappa/django-zappa-session.png

**Comment by bjinwright** [comment]
Notice how immediately after first request after logging in the sessionid value is gone.

**Comment by bjinwright** [comment]
This is the same behavior I noticed on the API Gateway version of the site.

**Comment by Miserlou** [comment]
The cookie thing is fixed in core (and I think the head of D-Z master now), but the admin forms won't work until "multipart/form-data" forms work. Previously, this was impossible, but they made a change to API GW earlier this week that might allow it to work, but I need to investigate further. Stay tuned..

**Comment by bjinwright** [comment]
Awesome

**Comment by Miserlou** [comment]
Okay, this is gonna work! I'm not all the way there yet but it'll pretty sure it will based on what I have so far. This means file uploads will work through Zappa too now.

**Comment by Miserlou** [comment]
Okay, I got it working!

**Comment by Miserlou** [comment]
Something going on the the cookies now.. grrrrr..

**Comment by Miserlou** [comment]
Okay! This should now be fixed in 0.13.0. You will need to call the 'deploy' command again so that the template mappings update.

**Comment by bjinwright** [comment]
I'm still seeing the logouts locally. Here is my pip freeze -l output.

base58==0.2.2
boto3==1.3.0
botocore==1.4.10
decorator==4.0.9
Django==1.9.5
django-zappa==0.13.0
docopt==0.6.2
docutils==0.12
futures==3.0.5
ipython==4.1.2
ipython-genutils==0.1.0
jmespath==0.9.0
lambda-packages==0.4.0
mysql-connector-python-rf==2.1.3
MySQL-python==1.2.5
path.py==8.2
pexpect==4.0.1
pickleshare==0.6
ptyprocess==0.5.1
python-dateutil==2.5.2
requests==2.9.1
simplegeneric==0.8.1
six==1.10.0
tqdm==4.4.0
traitlets==4.2.1
Unipath==1.1
Werkzeug==0.11.5
wheel==0.29.0
wsgi-request-logger==0.4.5
zappa==0.17.3

**Comment by Miserlou** [comment]
Locally? 

You'll need to remove the DjangoZappaMiddleware from your middleware, and you'll need to re-'deploy' for the new templates.

**Comment by bjinwright** [comment]
Update it works on Lambda. Except you can't update any records via admin. I suspect it is because there are only 4 parameters and to update records in admin you need at least 5. Realistically there might need to be 8. Where is the code that sets up the template for this? Maybe I can work on it.

**Comment by bjinwright** [comment]
https://youtu.be/fUrbDVLjekw

**Comment by Miserlou** [comment]
Ah, good catch!

You can update that with:

'parameter_depth': 10

which has a default of 5.

Again, this will require a different 'deploy'. I'm working on a 'redeploy' right now to avoid that.

I'll also increase the default.

**Comment by bjinwright** [comment]
Ahh! Awesome.
