### ISSUE TITLE
500 Internal Server Error?

### ISSUE THREAD

**Issue by powter234** [Miserlou/django-zappa#22]
I tried deploying, and keep getting this error when deploying Sphere.

~/.aws$ cat credentials
[default]
aws_access_key_id = [censored]
aws_secret_access_key = [censored]

The only file I really needed to change was spheres/production_settings.py

Followed the video, and seems like I'm just getting a 500 Internal Server Error?
https://l0723k4q1j.execute-api.us-east-1.amazonaws.com/production

**Comment by collingreen** [comment]
You can check the logs using cloudfront (there is a link at the top of your lamba console).

Also, if those are your actual AWS keys, you should go disconnect them immediately.

**Comment by mathom** [comment]
I've updated the issue and deleted them - make sure you cycle those out!

**Comment by powter234** [comment]
deleted. Thanks for the note. But I'm still wondering why this seems to only be happening to me? 500 Internal Server usually means that it reached the Django server but something wasn't working properly right? Could this be because of a recent merge?

I'm not very familiar with Cloudfront and how that helps with the logs.

**Comment by mathom** [comment]
I believe he meant cloudwatch - you can go to your function in the Lambda console and find a link to the function logs in cloudwatch from there. It should show you some more information about why it failed and gave the 500.

**Comment by collingreen** [comment]
I absolutely meant cloudwatch - sorry!

**Comment by powter234** [comment]
Does this mean I just need to create a log stream?

![screen shot 2016-02-22 at 12 34 44 am](https://cloud.githubusercontent.com/assets/17400303/13213217/1e075884-d8fc-11e5-8385-1e61e623820b.png)

**Comment by Miserlou** [comment]
You should just be able to 

python manage.py tail **your environment** 

now..

**Comment by mathom** [comment]
Also, the CloudWatch thing we were mentioning can be found by clicking the "View logs in CloudWatch" button on the right of the "Monitoring" tab in Lambda. Definitely try the `manage.py` method if you aren't comfortable with the AWS web console.

<img width="1235" alt="screen shot 2016-02-22 at 4 40 51 pm" src="https://cloud.githubusercontent.com/assets/399441/13235358/1d24aa84-d983-11e5-9e87-826f06eef615.png">

**Comment by collingreen** [comment]
Thanks for the details and screenshot @mathom -- much more helpful than my mis-named suggestion :stuck_out_tongue:

**Comment by powter234** [comment]
Don't worry about the Secret key :) I can change that. But here is what is happening:
![screen shot 2016-02-22 at 9 01 24 pm](https://cloud.githubusercontent.com/assets/17400303/13242343/af1628da-d9a8-11e5-954a-8260ed2f0280.png)
![screen shot 2016-02-22 at 9 02 20 pm](https://cloud.githubusercontent.com/assets/17400303/13242358/c6d66ca0-d9a8-11e5-8bf5-a54fc97e64e9.png)
```python
(spheres)~/Desktop/Spheres$ python manage.py tail dev
Traceback (most recent call last):
  File "manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/powter/.virtualenvs/spheres/lib/python2.7/site-packages/django/core/management/__init__.py", line 338, in execute_from_command_line
    utility.execute()
  File "/Users/powter/.virtualenvs/spheres/lib/python2.7/site-packages/django/core/management/__init__.py", line 330, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/powter/.virtualenvs/spheres/lib/python2.7/site-packages/django/core/management/base.py", line 390, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/powter/.virtualenvs/spheres/lib/python2.7/site-packages/django/core/management/base.py", line 441, in execute
    output = self.handle(*args, **options)
  File "/Users/powter/.virtualenvs/spheres/lib/python2.7/site-packages/django_zappa/management/commands/tail.py", line 68, in handle
    all_logs = zappa.fetch_logs(lambda_name)
  File "/Users/powter/.virtualenvs/spheres/lib/python2.7/site-packages/zappa/zappa.py", line 734, in fetch_logs
    orderBy='LastEventTime')
  File "/Users/powter/.virtualenvs/spheres/lib/python2.7/site-packages/botocore/client.py", line 310, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/Users/powter/.virtualenvs/spheres/lib/python2.7/site-packages/botocore/client.py", line 407, in _make_api_call
    raise ClientError(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ResourceNotFoundException) when calling the DescribeLogStreams operation: The specified log group does not exist.
(spheres)~/Desktop/Spheres$
```
![screen shot 2016-02-22 at 9 21 11 pm](https://cloud.githubusercontent.com/assets/17400303/13242521/525a92b4-d9aa-11e5-9ac6-3456745ffcfc.png)

![screen shot 2016-02-22 at 9 03 42 pm](https://cloud.githubusercontent.com/assets/17400303/13242373/ef2ef0d2-d9a8-11e5-9f3e-b6850e02a8b8.png)
![screen shot 2016-02-22 at 9 15 21 pm](https://cloud.githubusercontent.com/assets/17400303/13242441/75de7102-d9a9-11e5-98c7-e9524b27bf00.png)

Any ideas? Thanks in advance for all the help!

**Comment by mathom** [comment]
I was able to reproduce this by dumping out my IAM role and recreating it. I've fixed it in master since it was my fault :disappointed:

To get your project going, remove the IAM role that Zappa created and re-deploy with the master version installed. You can install it with the following:
`pip install -U git+https://github.com/Miserlou/Zappa.git`

**Comment by cancan101** [comment]
Is there any way to get zappa to delete the IAM role and lambda function? If not, I can file a ticket.

**Comment by mathom** [comment]
I'm actually looking into that now. Related to that, there's a snippet of code to check if an API exists by name but it uses the ID instead so I'm pretty sure it doesn't work as intended: https://github.com/Miserlou/Zappa/blob/master/zappa/zappa.py#L482-L492

**Comment by powter234** [comment]
@mathom did u get it to deploy correctly afterwards? I got this:

```python
(spheres)~/Desktop/Spheres$ python manage.py deploy dev
Creating ZappaLambdaExecution IAM..
...
...
  File "/Users/powter/.virtualenvs/spheres/lib/python2.7/site-packages/django_zappa/management/commands/deploy.py", line 75, in handle
    zappa.create_iam_roles()
  File "/Users/powter/.virtualenvs/spheres/lib/python2.7/site-packages/zappa/zappa.py", line 714, in create_iam_roles
    PolicyDocument=attach_policy_s)

...
...
botocore.exceptions.ClientError: An error occurred (MalformedPolicyDocument) when calling the PutRolePolicy operation: Syntax errors in policy.
```

Seems like it's not creating the IAM roles correctly

**Comment by mathom** [comment]
@powter234 yep, it was fixed in https://github.com/Miserlou/Zappa/commit/4c3ff5ad791b8926f3b64a3c918deb00f2f5651d

You may have the previous release installed. You can test it by installing from master via the pip command in https://github.com/Miserlou/django-zappa/issues/22#issuecomment-187981310

**Comment by powter234** [comment]
Hmm.. it's still not working for me. Is there like a slack channel I can join to get some help? I've been wanting to contribute but can't get started :(

**Comment by Miserlou** [comment]
There is as of.. right now! https://github.com/Miserlou/Zappa/issues/23

**Comment by Miserlou** [comment]
Here yo go powter: https://slackautoinviter.herokuapp.com/

**Comment by mathom** [comment]
@powter234 a new version of zappa has been published so you can just run `pip install -U zappa` and grab the latest version

**Comment by Miserlou** [comment]
Closing as it seems this is resolved, feel free to reopen if not.
